### PR TITLE
CF: Shortened the statement && Add countdown && Add timely notice

### PR DESCRIPTION
**Pull request by ligen131**
2CDRGGFQT_ J5PVEMD$26 Q
Support parsing educational contest and regular contest.

### CODE REVIEW

**Comment by gongchen618** [comment]
1. 年数 2022 的信息价值较少，如果删掉会更短
2. 是否加上距今天数/小时数，或者星期？可能比起日期会更加直观。
3. 关于主动行为：新插件 schedule 中设有临期提醒功能，或许可以给 codeforces 插件也写一个。（强烈建议！）

该 pr 会在今日晚些时候进行处理和部署。

**Comment by ligen131** [comment]
BTW, I think the config file can be changed to `default-example.yml` and add `default.yml` to `.gitignore` like other opensource project, so that every time the codes have been updated, we no need to change our config file when we do the localization testing.

That's why I changed `default.yml` to `user.yml` last time. May be I didn't explain it clearly.

**Comment by gongchen618** [comment]
哦！你是对的！我没有意识到这一点 :D

同样会在晚些时候进行修改。

**Comment by ligen131** [comment]
~V %9UIK8K0(T(K0$A1U_NM

**Comment by ligen131** [comment]
image
image
image

**Comment by ligen131** [comment]
> * 年数 2022 的信息价值较少，如果删掉会更短

Done.

> * 是否加上距今天数/小时数，或者星期？可能比起日期会更加直观。

Done. Added date & hour & min countdown.

> * 关于主动行为：新插件 schedule 中设有临期提醒功能，或许可以给 codeforces 插件也写一个。（强烈建议！）

Done. 2 hours and 10 minutes before the contest will notice (Don't forget to change group number in the config fire!) .

It seems that everything have been done. This PR is ready for review and merge.

**Comment by ligen131** [comment]
There are some conflicts. Emmm...

**Comment by ligen131** [comment]
I don't know how to resolve this. qwq

**Comment by ligen131** [comment]
OK. Resolved all the conflicts.

**Comment by gongchen618** [comment]
Nice!!!!!
Then, Before deploy the updated plugin, can I modify the format slightly? You see, the different digitals are kind of messed up when displayed on phone.
image

**Comment by ligen131** [comment]
Yes. It's up to you.

**Comment by gongchen618** [comment]
By the way, I'm doubt if the logs working healthily? There are so many of them but I don't know if they really indicate any bug. 
image
And you also forget to delete the DEBUG fmt.Println, on Line 68, codeforces.go. I commented it out for you.

**Comment by ligen131** [comment]
> There are so many of them but I don't know if they really indicate any bug.

Oh. I found it... That's my fault.


> And you also forget to delete the DEBUG fmt.Println, on Line 68, codeforces.go. I commented it out for you.

I didn't notice it. Sorry.

**Comment by gongchen618** [comment]
deployed!
image

**Pull request merged**
